version: '3'
services:

    config:
        container_name: config
        image: luisfernando2020/microservicos-softfocus:0.0.1-SNAPSHOT
        restart: always
        environment:
            URI: 'https://github.com/LuisFernandoBR2019/microservice-softfocus.git'
        ports:
          - 8888:8888
        expose:
          - 8888